### ISSUE TITLE
Installed target names do not match aliases

### ISSUE THREAD

**Issue by Som1Lse** [foonathan/lexy#107]
I noticed the names in the pull request do not match the aliases i.e.,  `foonathan::lexy_core` instead of `foonathan::lexy::core`.

It can be fixed, but might break someone, though my guess would be most people just use `add_subdirectory`. I can submit a pull request if there is interest.

This would make it easier to add it to `vcpkg`, since the target names are the same everywhere.

A slightly related thing I noticed was the install code is inside the main `CMakeLists.txt` rather than `src/CMakeLists.txt` with the targets, which I think is the more natural choice. (If a new target `lexy_foo` was added, one would only modify the second file.) I can include this change in the pull request as well, if there is interest.

**Comment by foonathan** [comment]
I agree with both points. Please make a PR.
