### ISSUE TITLE
CMake does not support the install target

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [foonathan/lexy#11]
The project can currently only be consumed via `add_subdirectory`. Are you waiting for the project to stabilize before you support this, or should I make a pr?

**Comment by foonathan** [comment]
I'm not sure. Is it possible to use the commit hash as a version number? Because that's the only one the project has at the moment.

**Comment by Ryan-rsm-McKenzie** [comment]
This will fetch the current commit hash, which you can then pass to the `project` command.
```cmake
execute_process(
    COMMAND "git" "rev-parse" "--short" "HEAD"
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    RESULT_VARIABLE LEXY_VERSION
    OUTPUT_QUIET
)
```

**Comment by foonathan** [comment]
I don't think that works, the version has to be integers separated by dots: https://cmake.org/cmake/help/latest/command/project.html?highlight=project#options

**Comment by Ryan-rsm-McKenzie** [comment]
You could convert the result into a decimal.
```cmake
execute_process(
    COMMAND "git" "rev-parse" "--short" "HEAD"
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE LEXY_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
math(EXPR LEXY_VERSION "0x${LEXY_VERSION}" OUTPUT_FORMAT DECIMAL)
```

**Comment by foonathan** [comment]
Yeah, that seems like too much magic. I'm closing this for now and will revisit it once I'm closer to an actual stable release.
