### ISSUE TITLE
as_collection has a hidden dependency on value_type

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [foonathan/lexy#12]
From here:
https://github.com/foonathan/lexy/blob/ccbd79c06715b14ffcf7326518412a4d705daf0c/include/lexy/callback.hpp#L335-L342
This can cause issues with collections that do not define a `value_type` when it does not map sense, such as a [trie](https://github.com/Tessil/hat-trie). An alternative would be to try to optionally detect `value_type`, or just defer to `emplace` since it can accept `value_type` itself, or construct it in place.

Also, this line function can end up invoking `initializer_list` overloads for collections that support them, which can end up as a compiler error:
https://github.com/foonathan/lexy/blob/ccbd79c06715b14ffcf7326518412a4d705daf0c/include/lexy/callback.hpp#L354-L357
An alternative would be to simply construct it as `_sink()`.

**Comment by foonathan** [comment]
> This can cause issues with collections that do not define a value_type when it does not map sense, such as a trie. An alternative would be to try to optionally detect value_type, or just defer to emplace since it can accept value_type itself, or construct it in place.

That is true. I'd probably fix it by taking any type `T` and SFINAE on `.insert()`, like `as_string` does: https://github.com/foonathan/lexy/blob/main/include/lexy/callback.hpp#L506
Then it also needs only one overload.

`as_list` has the same "problem": https://github.com/foonathan/lexy/blob/main/include/lexy/callback.hpp#L286

I'll fix it after I'm done with #10; but feel free to make a PR to fix it faster. ;)

> Also, this line function can end up invoking initializer_list overloads for collections that support them, which can end up as a compiler error:

I'm pretty sure it will always invoke the default constructor as that one has precedence over initializer list.

**Comment by Ryan-rsm-McKenzie** [comment]
In regards to the second issue, I found the real problem. [Aggregate initialization can fail here, in case of an explicit constructor](https://godbolt.org/z/E4xEbb).
https://github.com/foonathan/lexy/blob/ccbd79c06715b14ffcf7326518412a4d705daf0c/include/lexy/callback.hpp#L331
What really needs to happen, is this needs to be `T _result{};`. I just assumed it was something with `initializer_list` because it gets in the way of aggregate initialization all the time.

**Comment by Ryan-rsm-McKenzie** [comment]
Perhaps something like this could be used to choose a suitable overload?
```cpp
namespace _detail
{
    template <typename T, typename... Args>
    using _insert_invocable = decltype(LEXY_DECLVAL(T).insert(LEXY_DECLVAL(Args)...));
}

template <typename T>
struct _collection
{
    using return_type = T;

    template <typename... Args>
    constexpr T operator()(Args&&... args) const
    {
        // Use the initializer_list constructor.
        return T{LEXY_FWD(args)...};
    }

    struct _sink
    {
        T _result{};

        using return_type = T;

        template <typename... Args>
        void operator()(Args&&... args)
        {
            if constexpr (_detail::is_detected<_detail::_insert_invocable, T, Args...>)
            {
                _result.insert(LEXY_FWD(args)...);
            }
            else
            {
                _result.emplace(LEXY_FWD(args)...);
            }
        }

        T&& finish() &&
        {
            return LEXY_MOV(_result);
        }
    };
    constexpr auto sink() const
    {
        return _sink{};
    }
};
```

**Comment by foonathan** [comment]
Hm, I think that's too permissive. `std::set::insert` can also take iterator ranges and stuff, which right now uses `.emplace()` (I think that's right).

SFINAEI-ing for single arguments as I suggested above is the way to go IMO.
