### ISSUE TITLE
Surprising debug behavior when re-using `lexy::scan_result<>`

### ISSUE THREAD

**Issue by nickelpro** [foonathan/lexy#133]
I have no idea if this counts as a bug, it seems to be intended behavior but I don't understand why

Consider the following:

```cpp
namespace dsl = lexy::dsl;

struct word {
  static constexpr auto rule = dsl::identifier(dsl::ascii::alpha);
  static constexpr auto value = lexy::as_string<std::string>;
};

int main() {

  auto in {lexy::zstring_input("abc def")};

  auto scanner {lexy::scan(in, lexy_ext::report_error)};

  lexy::scan_result<std::string> result;

  while(scanner.branch<word>(result)) {
    fmt::print("{}\n", result.value());
    scanner.parse(dsl::whitespace(dsl::ascii::blank));
  }
}
```

This builds and runs as expected under a release build, but in a debug build hits the [precondition assert](https://github.com/foonathan/lexy/blob/59e3eed84748fb1af41077389680ede1dc5be8d2/include/lexy/_detail/lazy_init.hpp#L119) in lazy init.

This is maybe a documentation bug? Or I'm just dumb?

**Comment by foonathan** [comment]
It's a bug/oversight in the library, but fixed now.

**Comment by nickelpro** [comment]
Much appreciated :grinning:
