### ISSUE TITLE
lexy::nullopt can construct std::optional in an active state

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [foonathan/lexy#14]
https://godbolt.org/z/sjqG49

It seems to select overload 8) from [here](https://en.cppreference.com/w/cpp/utility/optional/optional).

**Comment by foonathan** [comment]
That's ... not ideal. I'll have to look into a fix.

**Comment by foonathan** [comment]
I've changed `lexy::nullopt` to be only convertible to `std::optional` and related types. This means the example code works now.

However, this breaks for example my JSON example as it used the fact that `lexy::dsl::opt()` gives you an object of essentially the same type in either case. I had to add `std::optional` members to the `json_number` struct, but this is nicer design anyway.
