### ISSUE TITLE
Use __cpp_nontype_template_args instead of __cpp_nontype_template_parameter_class

### ISSUE THREAD

**Issue by paul082** [foonathan/lexy#15]
Appears only GCC defines __cpp_nontype_template_parameter_class.

Also Cppreference makes no mention of a __cpp_nontype_template_parameter_class macro.  https://en.cppreference.com/w/cpp/feature_test

**Comment by foonathan** [comment]
It's a bit confusing, thanks for catching it. https://wg21.link/SD6 lists both as feature check macros, although I believe the feature from `__cpp_nontype_template_parameter_class` is no longer part of C++20. Anyways, I'll just check for both.
