### ISSUE TITLE
Add examples for parse

### ISSUE THREAD

**Issue by EmmanuelMess** [foonathan/lexy#163]
Add examples for https://lexy.foonathan.net/reference/action/parse/#parse page of documentation. In particular I have no idea how to use lexy::parse_result.

**Comment by foonathan** [comment]
Is that not enough? https://github.com/foonathan/lexy/blob/5e2601b3de57e979b5d23b8936cf040eb228fb94/examples/calculator.cpp#L457-L460

**Comment by EmmanuelMess** [comment]
I think I hallucinated there was a parse_result function.

**Comment by foonathan** [comment]
It's the return type of lexy::parse.
