### ISSUE TITLE
Support std::filesystem::path for input file

### ISSUE THREAD

**Issue by EmmanuelMess** [foonathan/lexy#167]
Support std::filesystem::path for input file:

```
const std::filesystem::path& path = ...;
const auto input = lexy::read_file<lexy::utf8_encoding>(path);
const auto result = lexy::parse<...>(input.buffer(), lexy_ext::report_error.path(path));
```

**Comment by Life4gal** [comment]
I don't think all users want to be burdened with the large number of dependencies that `filesystem` will bring.

And it's a clear violation of:
![image](https://github.com/foonathan/lexy/assets/52756109/2a5442fc-bdc5-4636-8a0a-6f0be59e0b8f)

I think it should be a trivial thing for you to convert `std::filesystem::path` to `std::string` (just for me, which I do), as opposed to adding `filesystem` as a dependency to lexy.
