### ISSUE TITLE
Static assertion failure in benchmarks/swar/main.cpp for MSVC

### ISSUE THREAD

**Issue by shohirose** [foonathan/lexy#179]
MSVC 2022 17.7.5 fails to compile due to the following static assertion failures:
```
static_assert failed: 'invalid template argument for uniform_int_distribution: N4950 [rand.req.genl]/1.5 requires 
    one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long'
static_assert failed: 'note: char, signed char, unsigned char, char8_t, int8_t, and uint8_t are not allowed'
```
These are caused by the use of `uniformt_int_distribution<char>` and `uniformt_int_distribution<char32_t>` in the `benchmarks/swar/main.cpp`.

**Comment by shohirose** [comment]
A quick fix is to use `uniform_int_distribution<int>` and cast to `char` or `char_32_t`:
```c++
char random_ascii()
{
    static std::uniform_int_distribution<int> dist(0x00, 0x7F);
    return static_cast<char>(dist(engine));
}

char32_t random_unicode()
{
    static std::uniform_int_distribution<int> dist(0x80, 0x10'FFFF);
    return static_cast<char32_t>(dist(engine));
}
```
But I am not sure if casting from int to char or char32_t is okay or not.

**Comment by foonathan** [comment]
Can you make a PR that uses `std::uint_least32_t` for the `random_unicode()` case?
