### ISSUE TITLE
Playground has gray text on a gray background

### ISSUE THREAD

**Issue by Bobini1** [foonathan/lexy#189]
![image](https://github.com/foonathan/lexy/assets/28908758/efa08590-5194-45c4-9a71-1b29723aa3d5)
https://lexy.foonathan.net/playground/
Am I the only one with this issue?

**Comment by foonathan** [comment]
You're probably using the dark mode of the website. There was a CSS bug which changed the foreground color of the text, but the graph background color is hardcoded. It should be fixed now (but the graph won't use a dark theme, sorry).

**Comment by Bobini1** [comment]
Thanks! The color scheme doesn't matter as long as it's readable.
