### ISSUE TITLE
Playground site fails to load samples

### ISSUE THREAD

**Issue by afeinman-snap** [foonathan/lexy#193]
If the playground is opened to load a specific sample (as is done in a few places in the documentation), the Load sample box no longer works. Mozilla shows javascript errors
The following link breaks the page: https://lexy.foonathan.net/playground/?example=scan
The regular link works: https://lexy.foonathan.net/playground/
Additionally, the sample names in the dropdown are prefixed with "/" - the likely problem is this [line](https://github.com/foonathan/lexy/blob/a8b98be28cc0b1a7a0cdf4c570e190193a3fe14e/docs/layouts/playground/playground.html#L11)

**Comment by foonathan** [comment]
Thanks! Fixed.
