### ISSUE TITLE
Typo: `spacing_mark` spelled `spaing_mark`

### ISSUE THREAD

**Issue by midrare** [foonathan/lexy#195]
I found a [small typo](https://github.com/foonathan/lexy/blob/a8b98be28cc0b1a7a0cdf4c570e190193a3fe14e/include/lexy/code_point.hpp#L88).

```cpp
LEXY_UNICODE_CATEGORY(Mc, spaing_mark)
                            -^-
```

**Comment by foonathan** [comment]
Thanks! Fixed.
