### ISSUE TITLE
C++14 support

### ISSUE THREAD

**Issue by olivierbichler-cea** [foonathan/lexy#196]
Is there any chance that C++14 may be supported? I guess C++17 is required for a wider support of constexpr, is there another reason?

**Comment by foonathan** [comment]
You can pry `if constexpr` from my cold, dead hands. ;)

I don't really want to go through the trouble of supporting even older compilers than the one I currently support anyway, sorry. If you manage to make it work with minimal edits (for example, clang supports `if constexpr` even in C++14 as an extension), I'll happily accept PRs, but won't officially maintain support.
