### ISSUE TITLE
"A!=-1" returns "operator cannot be mixed with previous operators" 

### ISSUE THREAD

**Issue by facontidavide** [foonathan/lexy#204]
Hi,

I created here an extension of your calculator tutorial, but I am straggling with the formula "A!=-1"

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp/scripting/operators.hpp

Is there any way to address this in the DSL?

**Comment by foonathan** [comment]
Can you send me a minimzed example that reproduces it on the playground? https://lexy.foonathan.net/playground/

**Comment by Aglargil** [comment]
> Can you send me a minimzed example that reproduces it on the playground? https://lexy.foonathan.net/playground/

The example in this document also has this error (operator cannot be mixed with previous operators)
https://lexy.foonathan.net/reference/dsl/expression/#groups
https://lexy.foonathan.net/playground/?id=on8bq76Yd&mode=tree
