### ISSUE TITLE
Install only defined if lexy is top level project

### ISSUE THREAD

**Issue by adamdusty** [foonathan/lexy#205]
Is there a reason that all the install rules are behind an if statement checking if source_dir is current_source_dir?

This makes it so if I use lexy in a library that also defines install targets, I have to manually include every lexy target (of which there are a few).

**Comment by foonathan** [comment]
I didn't imagine that people used it as `add_subdirectory` and then want to install their project. I thought for that use case you want to install lexy first, then call `find_package`.

But I welcome a PR that moves the install rules.
