### ISSUE TITLE
Location tracking.

### ISSUE THREAD

**Issue by rkaminsk** [foonathan/lexy#208]
Lexy already offers `lexy::dsl::position` to obtain the current input position. It would be nice to also have a rule to obtain where a rule starts and *ends*.

```
namespace lexy::dsl
{
    constexpr rule auto location(rule auto rule);
    constexpr branch-rule auto location(branch-rule auto rule);
}
```
The semantic value of location should be a pair of positions. The first should be the iterator before the rule as would also be obtained with `lexy::dsl::position` and the second the position right after the rule.

Currently, it is a bit complicated to obtain something like this. Especially with automatic white space skipping.

**Comment by foonathan** [comment]
You can use [`dsl::capture`](https://lexy.foonathan.net/reference/dsl/capture/#capture) for that; it gives you a `lexy::lexeme`. Note that it requires token rules or token productions, which is intentional: it is not clear what to do if you want with trailing whitespace.

If you don't care about whitespace, I think using `dsl::position` twice explicitly makes that clear.

**Comment by rkaminsk** [comment]
Just some thoughts why I think that this would be a useful feature.

Given a production
```
x ::= a b
```
there is no nice generic solution to obtain where `a` ends only where `b` starts because the white space after `a` will be gobbled. `capture` does not help either because it does not work in general. Not using the inbuilt white space handling is also annoying because it clutters the grammar. One can of course make the position part of the semantic value of `a` because it has to boil down to a lexeme at some point - but this is also not very nice.

On another note, this is something that is super easy in a parser generator like bison.

**Comment by foonathan** [comment]
Yeah, this is tricky with my model. Like in my whitespace model, trailing whitespace is logically part of the production, not something that is between productions.

Note that you can turn `a` into a token production which you can then capture. Inside a token production, you can use whitespace again. It's a bit of a hack, but should work.

**Comment by rkaminsk** [comment]
If I remember correctly, token productions also have limitations.

But this is also not of great importance to me anymore because finally I decided to rewrite my parser by hand. The compile was one of the major issues here. At least converting the lexy grammar was more or less straight-forward because the required lookahead was nicely visible.

**Comment by foonathan** [comment]
> The compile was one of the major issues here

The compile time?

**Comment by rkaminsk** [comment]
> > The compile was one of the major issues here
> 
> The compile time?

Yes, the compile time.
