### ISSUE TITLE
parse without a file

### ISSUE THREAD

**Issue by haasdo95** [foonathan/lexy#21]
It is my understanding that currently lexy::parse only accepts a file returned by lexy::read_file. Is it possible to let lexy::parse accept a std::string?
I know this is not strictly necessary: this is a parser after all. But this feature will prove useful for unit testing. 
Thanks!

**Comment by foonathan** [comment]
The `lexy::parse` function accepts an arbitrary `Input`. The buffer returned by `lexy::read_file` is one, but there are multiple others: https://lexy.foonathan.net/reference/#_the_pre_defined_inputs

You want the `lexy::string_input`: https://lexy.foonathan.net/reference/#_string_input

```cpp
std::string str = ...;
auto result = lexy::parse<production>(lexy::string_input(str), …);
```
