### ISSUE TITLE
Documentation addition: Advice on rules

### ISSUE THREAD

**Issue by ninkibah** [foonathan/lexy#214]
In most of the documentation, rules are initialized with a dsl expression, but in many of the examples, they are initialized with an immediately executed lambda.

For example:
```
struct dataMember
{
    static constexpr auto rule = [] {
        auto head = dsl::ascii::alpha_underscore;
        auto tail = dsl::ascii::alpha_digit_underscore;
        return dsl::identifier(head, tail);
    }();
};
// Could also be written:
struct dataMember
{
    static constexpr auto head = dsl::ascii::alpha_underscore;
    static constexpr auto tail = dsl::ascii::alpha_digit_underscore;
    static constexpr auto rule = dsl::identifier(head, tail);
};
```

Is there a reason to prefer one way over the other?

**Comment by Spartan322** [comment]
The easiest reason for the lambdas is you don't leak the variables, so in the least its lexy's form of private encapsulation.

**Comment by ninkibah** [comment]
Thanks for the answer. Very reasonable.

**Comment by ninkibah** [comment]
I'm closing this issue, as spartan322 has answered it sufficiently, but also as I should have created it a discussion instead.
