### ISSUE TITLE
Compiler error on MSVC

### ISSUE THREAD

**Issue by mathijs727** [foonathan/lexy#25]
The use of `#warning` in `include/lexy/error_location.hpp` at line 13 is not supported on MSVC and results in a fatal error:
> ...\lexy\include\lexy\error_location.hpp(13): fatal error C1021: invalid preprocessor command 'warning'

This issue can be easily replicated in Compiler Explorer:
https://godbolt.org/z/7nbe8TjKh

**Comment by foonathan** [comment]
Well, the entire header is deprecated anyway, so just don't include it?
