### ISSUE TITLE
Add cmake install target

### ISSUE THREAD

**Issue by autoantwort** [foonathan/lexy#26]
I wanted to add lexy to vcpkg but this requires an install target. Alternatively I could copy all files manually but I thing a install target is a cleaner solution.  
Nice project! :)

**Comment by foonathan** [comment]
See the discussion at #11. The project is not quite* stable enough at the moment to assign it a version number; would that work with vcpkg?

* I plan on tagging the first release at the end of summer.

**Comment by autoantwort** [comment]
Yeah that work with vcpkg, you don't need a version number

**Comment by foonathan** [comment]
Alright then. Can you do a PR to add the appropriate install target you want?

**Comment by zzk666666** [comment]
Hallo Sir, ich bin ein Student aus China, können wir voneinander Programmieren lernen
