### ISSUE TITLE
Add support for binary parsers

### ISSUE THREAD

**Issue by dominiklohmann** [foonathan/lexy#27]
This is a feature request to add support for binary parsers similar to [Spirit X3's binary parsers](https://www.boost.org/doc/libs/1_76_0/libs/spirit/doc/x3/html/spirit_x3/quick_reference/binary.html). I have been keeping an eye on this library for quite a while now and really enjoy working with it, especially because of the parser error handling, which is just nonexistent In most other parser libraries.

A major roadblock in adoption of lexy for me is the lack of utilities for working with binary input. How would I go about adding building blocks to the DSL for that, e.g., have a literal in the DSL representing a known integer that is represented as a 16 bit big-endian binary? E.g., I have a binary format that contains a version prefix at the very beginning that is one of a set of a supported values. Some form of `dsl::big_word_lit<1> | dsl::big_word_lit<2> | dsl::error<unknown_version>`.

**Comment by foonathan** [comment]
Adding binary parsers is planned.

What I'm currently thinking about adding (names etc. not finalized):

* `dsl::byte_lit<a, b, c>`: parse the bytes `a`, `b`, `c` (similar to `LEXY_LIT()` but without the text encoding stuff)
* `dsl::byte`: parse a single arbitrary byte
* `dsl::bytes<N>`: parse `N` arbitrary bytes
* `dsl::bit_cast<T>`: parse an object of type `T` by simply bit casting it (this has endian issues, so I'm not sure how useful it is?)
* similar to Spirit, facilities for parsing big endian/little endian integers of specific size
* some facility for parsing an integer and then parsing that many bytes

**Comment by dominiklohmann** [comment]
> * `dsl::byte_lit<a, b, c>`: parse the bytes `a`, `b`, `c` (similar to `LEXY_LIT()` but without the text encoding stuff)
> * `dsl::byte`: parse a single arbitrary byte

These all sound good as described.

> * `dsl::bytes<N>`: parse `N` arbitrary bytes

I think this should not be included. Unlike a combination of multiple `dsl::byte` parsers it is not immediately obvious if this accounts for endianness, so it's probably better to have the user express this manually.

> * `dsl::bit_cast<T>`: parse an object of type `T` by simply bit casting it (this has endian issues, so I'm not sure how useful it is?)

If people want to do this, they can always use `dsl::bytes<sizeof(T)>` or similar and do the bit-casting themselves. I don't think this should be included in the library as it's way too easy to do mistakes of the "works on my machine" kind with it.

> * similar to Spirit, facilities for parsing big endian/little endian integers of specific size

These are the binary parsers that I think are most important for a parser library to provide, as they're hard to get right for users.

> * some facility for parsing an integer and then parsing that many bytes

Can you elaborate on this? It's not immediately clear what you mean to me.

**Comment by foonathan** [comment]
> > * `dsl::bytes<N>`: parse `N` arbitrary bytes
> 
> I think this should not be included. Unlike a combination of multiple `dsl::byte` parsers it is not immediately obvious if this accounts for endianness, so it's probably better to have the user express this manually.

Fair enough, especially since `dsl::times<N>(dsl::byte)` works (it didn't in the past, as this hypothetical byte rule wouldn't produce a value).
 
> > * `dsl::bit_cast<T>`: parse an object of type `T` by simply bit casting it (this has endian issues, so I'm not sure how useful it is?)
> 
> If people want to do this, they can always use `dsl::bytes<sizeof(T)>` or similar and do the bit-casting themselves. I don't think this should be included in the library as it's way too easy to do mistakes of the "works on my machine" kind with it.

Right.
 
> > * some facility for parsing an integer and then parsing that many bytes
> 
> Can you elaborate on this? It's not immediately clear what you mean to me.

It's for parsing a format `<size><size bytes>`. The idea would be something like `dsl::n_bytes(dsl::uint32_big_endian)`, which would read a uint32 and then skip that many bytes.

**Comment by foonathan** [comment]
Rules for byte input are now implemented. I've decided to add `dsl::bytes<N>`: it doesn't produce a value, so there can't be any endianness confusion. I've also added a callback `lexy::bit_cast`.

An example parses a serialized protobuf message: https://github.com/foonathan/lexy/blob/main/examples/protobuf.cpp

Let me know if you need anything else!
