### ISSUE TITLE
Context sensitive optimization

### ISSUE THREAD

**Issue by matthieugras** [foonathan/lexy#29]
Let's say I want to parse a list of predicates of the form:
`A(x,y,...)`
and I have an external map from predicate names to argument types (so that I know how to parse the predicates' arguments). With lexy, I can write a sink that takes an immutable parse state (in this case my map from names to lists of types) and parses the arguments into the correct types. Then I would parse predicates like this:

```
struct predicate {
rule = lexy::p<predicate_name> + lexy::p<argument_list>
value = my_sink(....)
}
```
where the value of `argument_list` is vector of strings.

The problem I have is that I have to parse `argument_list` into a vector of strings. If I could first parse `predicate_name` and add this information to the parse state so that I know the name of the predicate while computing the value of `argument_list`, I wouldn't have to delay the decision of how to parse the arguments. Is there a way to achieve this with lexy?

**Comment by foonathan** [comment]
As a first optimization, you can construct a `std::vector` of `lexy::lexeme`s, which doesn't require an allocation for the string part at least: https://lexy.foonathan.net/reference/lexeme/

But yes, this sort of context-sensitive parsing is currently not easily possible. I plan on adding something like this:

```cpp
struct predicate
{
    static constexpr auto rule = dsl::manual_parser(&do_parse);

    static lexy::result<ast::predicate> do_parse(lexy::stream& input)
    {
        auto name = input.parse<predicate_name>();
        if (!name)
            return {};

        if (!input.match(dsl::lit_c<'('>))
            return {};

        if (name.value() == "A")
        {
            auto a = input.parse<integer>();
            if (!input.match(dsl::comma))
                return {};

            auto b = input.parse<variable>();
            if (!input.match(dsl::comma))
                return {};

            if (!input.match(dsl::lit_c<')'>))
                return {};

            return ast::predicate(name.value(), a, b);
        }
        else …
    }
};
```

That is, you have a rule that will invoke a custom function for parsing. This function then receives some form of safe abstraction of the input, where you can't look at individual characters directly like the rules do (for safety reasons), but instead can delegate to other productions or rules. In that function, you can parse it however you want.

**Comment by matthieugras** [comment]
Thanks, that'll do for my purpose!
The API you are proposing would solve the problem very nicely.

**Comment by foonathan** [comment]
This is now implemented with `dsl::scan`: https://lexy.foonathan.net/reference/dsl/scan/#scan

**Comment by matthieugras** [comment]
Works great. Thank you 👍🏻
