### ISSUE TITLE
IPv4 example does not consume entire input

### ISSUE THREAD

**Issue by rokups** [foonathan/lexy#3]
IPv4 parsing example happily accepts `"192.168.1.1x00"` and `"x00"` bit is happily ignored. Should it not report an error?

**Comment by foonathan** [comment]
"should" is relative.

The code as written does not consume entire input that is correct, but this is not a bug in the library: unless you tell it, it does not consume the entire input.

However, the example implementation should probably do that? I'll fix it.

**Comment by rokups** [comment]
If that is out of scope of example, a comment indicating the behavior would suffice to clear the confusion. Thanks :+1: 

(library looks amazing!)

**Comment by foonathan** [comment]
No, I just forgot :D The example was originally meant to illustrate dsl::times so kept very minimal. It's just a matter of adding a `+ dsl::eof` at the end.
