### ISSUE TITLE
dsl::identifier(token) is not equivalent to dsl::capture(dsl::while_(token)) if wrapped in a list

### ISSUE THREAD

**Issue by benjaminwinger** [foonathan/lexy#33]
Narrowed this down from what was mentioned in https://github.com/foonathan/lexy/pull/28#issuecomment-927217313

E.g. [this example from the playground](https://godbolt.org/clientstate/eyJzZXNzaW9ucyI6W3siaWQiOjEsImxhbmd1YWdlIjoiYysrIiwic291cmNlIjoiI2RlZmluZSBMRVhZX1BMQVlHUk9VTkRfUFJPRFVDVElPTiBSZXNvdXJjZVxuI2luY2x1ZGUgPGxleHkvZHNsLmhwcD5cblxubmFtZXNwYWNlIGRzbCA9IGxleHk6OmRzbDtcblxuLy89PT0gZ3JhbW1hciA9PT0vL1xuc3RhdGljIGNvbnN0ZXhwciBhdXRvIHRleHRfY2hhciA9XG4gICAgZHNsOjpjb2RlX3BvaW50IC0gZHNsOjpsaXRfYzwneyc%2BIC0gZHNsOjpsaXRfYzwnfSc%2BIC0gZHNsOjpuZXdsaW5lO1xuc3RhdGljIGNvbnN0ZXhwciBhdXRvIGJsYW5rX2lubGluZSA9IGRzbDo6d2hpbGVfb25lKGRzbDo6bGl0X2M8JyAnPik7XG5cbnN0cnVjdCBJZGVudGlmaWVyIDogbGV4eTo6dG9rZW5fcHJvZHVjdGlvbiB7XG4gICAgc3RhdGljIGNvbnN0ZXhwciBhdXRvIHJ1bGUgPSBbXSB7XG4gICAgICAgIGF1dG8gaGVhZCA9IGRzbDo6YXNjaWk6OmFscGhhX3VuZGVyc2NvcmU7XG4gICAgICAgIGF1dG8gdGFpbCA9IGRzbDo6YXNjaWk6OmFscGhhX2RpZ2l0X3VuZGVyc2NvcmUgLyBkc2w6OmxpdF9jPCctJz47XG4gICAgICAgIHJldHVybiBkc2w6OmlkZW50aWZpZXIoaGVhZCwgdGFpbCk7XG4gICAgfSgpO1xufTtcblxuc3RydWN0IGlubGluZV90ZXh0IDogbGV4eTo6dG9rZW5fcHJvZHVjdGlvbiB7XG4gICAgLy9zdGF0aWMgY29uc3RleHByIGF1dG8gcnVsZSA9IGRzbDo6Y2FwdHVyZShkc2w6OndoaWxlX29uZSh0ZXh0X2NoYXIpKTtcbiAgICBzdGF0aWMgY29uc3RleHByIGF1dG8gcnVsZSA9IGRzbDo6aWRlbnRpZmllcih0ZXh0X2NoYXIpO1xufTtcblxuc3RydWN0IE1lc3NhZ2Uge1xuICAgIHN0YXRpYyBjb25zdGV4cHIgYXV0byB3aGl0ZXNwYWNlID0gZHNsOjpsaXRfYzwnICc%2BO1xuICAgIHN0YXRpYyBjb25zdGV4cHIgYXV0byBydWxlID0gW10ge1xuICAgICAgICAvLyBTZWVtcyB0byB3b3JrIGFzIGV4cGVjdGVkIGlmIHRoaXMgaXMgcmVwbGFjZWQgd2l0aCBkc2w6OnA8aW5saW5lX3RleHQ%2BXG4gICAgICAgIGF1dG8gdmFsdWUgPSBkc2w6Omxpc3QoZHNsOjpwPGlubGluZV90ZXh0Pik7XG5cbiAgICAgICAgcmV0dXJuIGRzbDo6cDxJZGVudGlmaWVyPiA%2BPiBkc2w6OmxpdF9jPCc9Jz4gKyB2YWx1ZSArIGRzbDo6bmV3bGluZTtcbiAgICB9KCk7XG59O1xuXG5zdHJ1Y3QgRW50cnkgOiBsZXh5Ojp0b2tlbl9wcm9kdWN0aW9uIHtcbiAgICBzdGF0aWMgY29uc3RleHByIGF1dG8gcnVsZSA9IGRzbDo6cDxNZXNzYWdlPjtcbn07XG5cbnN0cnVjdCBSZXNvdXJjZSB7XG4gICAgc3RhdGljIGNvbnN0ZXhwciBhdXRvIHJ1bGUgPSBkc2w6OnRlcm1pbmF0b3IoZHNsOjplb2YpLm9wdF9saXN0KFxuICAgICAgICBkc2w6OnA8RW50cnk%2BKTtcbn07XG4vLz09PSBtYWluIGZ1bmN0aW9uID09PS8vXG4jaW5jbHVkZSA8bGV4eS9hY3Rpb24vcGFyc2VfYXNfdHJlZS5ocHA%2BXG4jaW5jbHVkZSA8bGV4eS92aXN1YWxpemUuaHBwPlxuI2luY2x1ZGUgPGxleHlfZXh0L2NvbXBpbGVyX2V4cGxvcmVyLmhwcD5cbiNpbmNsdWRlIDxsZXh5X2V4dC9yZXBvcnRfZXJyb3IuaHBwPlxuXG5pbnQgbWFpbigpXG57XG4gICAgYXV0byBpbnB1dCA9IGxleHlfZXh0Ojpjb21waWxlcl9leHBsb3Jlcl9pbnB1dCgpO1xuXG4gICAgbGV4eTo6cGFyc2VfdHJlZV9mb3I8ZGVjbHR5cGUoaW5wdXQpPiB0cmVlO1xuICAgIGF1dG8gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcmVzdWx0XG4gICAgICAgID0gbGV4eTo6cGFyc2VfYXNfdHJlZTxMRVhZX1BMQVlHUk9VTkRfUFJPRFVDVElPTj4odHJlZSwgaW5wdXQsIGxleHlfZXh0OjpyZXBvcnRfZXJyb3IpO1xuXG4gICAgbGV4eTo6dmlzdWFsaXplKHN0ZG91dCwgdHJlZSwge2xleHk6OnZpc3VhbGl6ZV9mYW5jeX0pO1xuXG4gICAgaWYgKCFyZXN1bHQpXG4gICAgICAgIHJldHVybiAxO1xufVxuXG4iLCJjb21waWxlcnMiOltdLCJleGVjdXRvcnMiOlt7ImNvbXBpbGVyIjp7ImlkIjoiY2xhbmdfdHJ1bmsiLCJsaWJzIjpbeyJpZCI6ImxleHkiLCJ2ZXJzaW9uIjoidHJ1bmsifV0sIm9wdGlvbnMiOiItc3RkPWMrKzIwIn0sInN0ZGluIjoiaWQgPSBwYXR0ZXJuXG4iLCJzdGRpblZpc2libGUiOnRydWV9XX1dfQ%3D%3D).

`id = pattern\n` should be a valid input, and it works when `inline_text` is `dsl::capture(dsl::while_one(text_char))`.
It also is fixed if the message takes a `dsl::p<inline_text>` directly instead of a `dsl::list(dsl::p<inline_text>)`.

**Comment by foonathan** [comment]
Playground link: https://lexy.foonathan.net/playground/?id=33s3We6Ms&mode=tree

**Comment by foonathan** [comment]
This was fixed by 9cbb300501fd614dde181751e74d2bd5e120f5e8.
