### ISSUE TITLE
Tutorial example fails to compile

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [foonathan/lexy#4]
I'm compiling with MSVC which obviously doesn't compile the project for many reasons, but here's one error that stood out to me.

From what I gather, this conditional enabler here tries to detect a static method `name` on the object, so that it can produce a type name:
https://github.com/foonathan/lexy/blob/733f3b6386e4333e07ee21be65fb647eda965c7f/include/lexy/_detail/type_name.hpp#L65-L66  
However, in the tutorial, there's a type `grammar::name`, which, when plugged into this function here:
https://github.com/foonathan/lexy/blob/733f3b6386e4333e07ee21be65fb647eda965c7f/examples/tutorial.cpp#L123  
It evaluates to `grammar::name::name()`. This invokes the constructor, and is thus a valid expression, but obviously it doesn't return a string. Perhaps the conditional enabler could exclude expressions for which `T::name` yields a type name?

**Comment by foonathan** [comment]
That's probably a good idea.

I can also look into trying to get MSVC compile the examples at least. It really doesn't like the unit tests as they're tested at compile time and I don't really want to use a TEST_CONSTEXPR macro *everywhere*.

**Comment by Ryan-rsm-McKenzie** [comment]
I actually got it to compile the json test with `/Zc:preprocessor` and two minor changes to the source code. In particular, `_try` is a reserved keyword which aliases `__try` for compatibility reasons and can't be used as an identifier. I'll post the exact changes when I have the time.

**Comment by foonathan** [comment]
That would be really helpful!

**Comment by Ryan-rsm-McKenzie** [comment]
This is fixed by #5
