### ISSUE TITLE
cpp_comment example in playground is incomplete

### ISSUE THREAD

**Issue by Xottab-DUTY** [foonathan/lexy#42]
Current cpp_comment example implementation:
```cpp
struct production
{
    // Note that `dsl::eol` matches EOF as well, so `.or_eof()` is implied.
    static constexpr auto rule = LEXY_LIT("//") + dsl::until(dsl::eol);
};
```

The current implementation doesn't take into account the backslash (`\`):
```cpp
// in C++ \
the second line will be also recognized as comment, because of backslash, \
but cpp_comment example doesn't handle that. (this line is also a comment)
```

**Comment by foonathan** [comment]
This is true. A correct implementation would look something like this: https://lexy.foonathan.net/playground/?id=sYj6qc6c3&mode=tree

However, the example is only meant to demonstrate the `dsl::until()` rule. The "cpp_comment" doesn't refer to "comments as in C++", but more C++-style comments (// until newline). For example, Rust has C++ style comments without backslash.

**Comment by Xottab-DUTY** [comment]
Thank you! I was struggling with implementing this myself, because I'm new to lexy :)
