### ISSUE TITLE
Assertion failed when using lexy_ext::report_error

### ISSUE THREAD

**Issue by jannikw** [foonathan/lexy#48]
I stumbled upon a failing assertion that can be triggered when using `lexy_ext::shell` and `lexy_ext::report_error` as in the shell example (with slight modifications).

Here is how you can reproduce it. First, modify the echo rule in such a way that is expects any kind of literal token after the initial keyword. Any of the following has the same effect:
```cpp
struct cmd_echo
{
    static constexpr auto rule  = LEXY_KEYWORD("echo", identifier) >> LEXY_LIT("abc") + dsl::p<argument>;
    // static constexpr auto rule  = LEXY_KEYWORD("echo", identifier) >> dsl::lit_c<'a'> + dsl::p<argument>;
    // static constexpr auto rule  = LEXY_KEYWORD("echo", identifier) >> dsl::round_bracketed( dsl::p<argument>);
    static constexpr auto value = lexy::new_<shell::cmd_echo, shell::command>;
};
```
Now start the shell and enter only the keyword `echo`. Then press <kbd>Ctrl</kbd>+<kbd>D</kbd>. This sends the current input on to parsing and makes lexy consume the initial keyword.  Thus, it expects the literal token next. Now end the input completely by pressing <kbd>Ctrl</kbd>+<kbd>D</kbd> again. Parsing the command fails, because of the missing literal token and `lexy_ext::report_error` is called.

Writing the annotation for the expected token then causes the assertion to fail. The `+ 1` in `error.index() + 1` causes the iterator to be moved past its end.
```cpp
    // Write the main annotation.
    if constexpr (std::is_same_v<Tag, lexy::expected_literal>)
    {
        auto string = lexy::_detail::make_literal_lexeme<typename Reader::encoding>(error.string());

        out = writer.write_annotation(out, annotation_kind::primary, location,
                                      lexy::_detail::next(error.position(), error.index() + 1), // <----- HERE
                                      [&](OutputIt out, lexy::visualization_options opts) {
                                          out = lexy::_detail::write_str(out, "expected '");
                                          out = lexy::visualize_to(out, string, opts);
                                          out = lexy::_detail::write_str(out, "'");
                                          return out;
                                      });
    }
```

The following assertion fails:
https://github.com/foonathan/lexy/blob/7b4b499d37eed72b4bd90710a4511bbc81830532/include/lexy/_detail/buffer_builder.hpp#L127

Removing the the `+ 1` and just leaving it as `error.index()` actually fixes the problem. Error messages still look good for the cases I could test. But I am not sure, if this is test best way to fix it as I don't really know how important the `+1` is there.

Checkout https://github.com/jannikw/lexy/commit/617f5244d295d6693173b8c25cb23e38ac63de84 for reproducing this and https://github.com/jannikw/lexy/commit/5e4afce355cebba4208a9775095a1a33c0201345 for the potential fix.

**Comment by foonathan** [comment]
Thanks for noticing, fixed.

> Removing the the + 1 and just leaving it as error.index() actually fixes the problem. Error messages still look good for the cases I could test. But I am not sure, if this is test best way to fix it as I don't really know how important the +1 is there.

The range controls what is being highlighted/underlined in the error message. For an `expected_literal` error, I want to underline everything that could be matched from the literal plus the character that is wrong. Without the `+ 1`, it just underlines everything that is correct, which seems wrong.

**Comment by jannikw** [comment]
Thank you for the quick fix.

> The range controls what is being highlighted/underlined in the error message. For an expected_literal error, I want to underline everything that could be matched from the literal plus the character that is wrong. Without the + 1, it just underlines everything that is correct, which seems wrong.

Makes sense. I was thinking it would be something like this, I just couldn't spot the difference between the two. But I guess this was maybe because it was just pointing into some whitespace, making it hard see any differences when I checked.
