### ISSUE TITLE
Including lexy in CMake project forces use of C++20

### ISSUE THREAD

**Issue by lacc97** [foonathan/lexy#55]
In `src/CMakeLists.txt:123`, the lexy CMake project checks whether the cxx compiler supports c++20 and if so, unconditionally enables it. This in turn gets propagated as part of the INTERFACE properties of the lexy targets, which means even if the user has specified C++17 for the toplevel project, this gets overriden by lexy.

The [CMake docs for 3.8](https://cmake.org/cmake/help/v3.8/manual/cmake-compile-features.7.html#requiring-language-standards) suggest using any of the cxx_std_?? compiler features guarantees at least that version will be used for compilation so it should be fine to just use cxx_std_17 in the compile features and let the user choose C++20 on her own. [More recent docs](https://cmake.org/cmake/help/v3.23/manual/cmake-compile-features.7.html#requiring-language-standards) make this more explicit.

**Comment by foonathan** [comment]
This was done intentionally for a couple of reasons:

* The library works better in C++20, e.g. `LEXY_LIT()` isn't needed anymore, and you can use `dsl::lit`.
* I don't want to support the same compiler in multiple language modes: if you have a compiler that supports enabling of C++20, I don't want to support it using C++17 as well.
* In my experience, the available use of C++ features is gated behind the oldest compiler you need to support, not behind some language standard.

Can you explain, why you can't enable C++20, even though you have a C++20 compatible compiler?

**Comment by lacc97** [comment]
I am targeting a compiler that doesn't support C+20. I was just going through the tutorials and getting familiarised with lexy in an environment with a C++20 compiler, so I was a bit surprised when my CMake project was being built as C++20 even though I had instructed it to use C++17.

My issue is that I wasn't expecting a library that support C++17 as minimum standard to suddenly require C++20 mode in CMake, but I can understand if you don't want to support multiple combinations of compile options for the same compiler.
