### ISSUE TITLE
why save reader before match(reader) ?

### ISSUE THREAD

**Issue by netcan** [foonathan/lexy#6]
https://github.com/foonathan/lexy/blob/e82030f326f4def228b78b11dc1ca54b95eb8aae/include/lexy/dsl/choice.hpp#L41

I read the code when matching fail, it doesn't change the reader; when matching success, it bumps the reader.
so why needs to save the reader and while fail to restore it?

**Comment by foonathan** [comment]
The then_matcher resets on failure, yes. However, by this point we have still consumed the condition. The general rule is that matchers need to reset everything on failure, so we need to reset that as well.

But thanks for pointing that out! I think I can remove the matcher from choice entirely; I added it before `while_(choice)` worked and a choice as pattern is no different than alternative and it is dangerous to pretent it would honor the branches while making decisions.
