### ISSUE TITLE
is `operator/` useless? `operator|` offers same semantics

### ISSUE THREAD

**Issue by netcan** [foonathan/lexy#7]
```
lexy::dsl::operator|
lexy/dsl/choice.hpp
branch  | branch  : Rule
pattern | pattern : Pattern
```

```
lexy::dsl::operator/
lexy/dsl/alternative.hpp
pattern / pattern : Pattern
```

I read the docs and code, is `operator/` useless? both to offer same semantics...

**Comment by netcan** [comment]
oh, I find difference is that `operator/` when failed doesn't recover reader...

**Comment by foonathan** [comment]
My plan is to change it, such that | is always a branch aware rule and / a backtracking pattern.

**Comment by netcan** [comment]
> My plan is to change it, such that | is always a branch aware rule and / a backtracking pattern.

good idea, let `|` to aware pattern 👍

**Comment by foonathan** [comment]
This actually does not work, as choice needs to be a pattern for whitespace.

So for now the only difference is that choice is branch aware, i.e.

```
LEXY_LIT("a") >> LEXY_LIT("bc") | LEXY_LIT("ab")
```

would never match `abc` as the condition `a` takes precedence always.

I plan on optimizing alternative to use a trie like algorithm for efficiently matching multiple patterns at once.
