### ISSUE TITLE
benchmar compile errors

### ISSUE THREAD

**Issue by MyraBaba** [foonathan/lexy#83]
Hi, 

Would you mind to make benchmark compile-able from the main Cmake to find all dependencies and libraries ? 

Otherwise there are many errors.

Best

**Comment by foonathan** [comment]
It does compile using CMake? You have to generate it with `LEXY_BUILD_BENCHMARKS=ON`, then you can build and run the target as documented here: https://lexy.foonathan.net/learn/build/#_development_build

What errors are you getting?
