### ISSUE TITLE
Infinite compilation caused by dsl::times with separator and automatic whitespace

### ISSUE THREAD

**Issue by andrei-datcu** [foonathan/lexy#84]
Minimal repro case: [https://godbolt.org/z/44hTdPzza](https://godbolt.org/z/44hTdPzza)
Reproduces on clang 13, clang 14 and gcc 12

This doesn't happen if either of the following is true:

- automatic whitespace isn't enabled
- no separator is specified for `dsl::times`

L.E:  In the mean time I discovered `lexy::token_production` and that makes things a bit better, but the general problem remains: If automatic whitespace is enabled, then chaining too many rules will make the compilation times explode. For instance, a simple
```
struct production {
    constexpr auto whitespace = dsl::ascii:space;
    constexpr auto rule = LEXY_LIT("why") +  LEXY_LIT("oh") +  LEXY_LIT("why") +  LEXY_LIT("is") +  LEXY_LIT("this") +  LEXY_LIT("taking") +  LEXY_LIT("so ") +  LEXY_LIT("so") +  LEXY_LIT("so") +  LEXY_LIT("oh") +  LEXY_LIT("so") +  LEXY_LIT("long");
};
```
seems to never finish compiling.

**Comment by foonathan** [comment]
Thanks for noticing. Should be fixed now.
