### ISSUE TITLE
`utf8_char_encoding::eof()` produces warning C4310 on MSVC

### ISSUE THREAD

**Issue by Xottab-DUTY** [foonathan/lexy#91]
`utf8_char_encoding::eof()` produces warning C4310 on MSVC

https://github.com/foonathan/lexy/blob/e7c74d1fcb88a220a6803f6b59f722f84a756f24/include/lexy/encoding.hpp#L122

https://learn.microsoft.com/en-gb/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4310?view=msvc-160

**Comment by foonathan** [comment]
That's a silly warning, and enabled by W4. The library does not aim to be clean on W4.
